### ISSUE TITLE
Possible to use Iodine with Sidekiq or in Rails Console?

### ISSUE THREAD

**Issue by lucaskuan** [boazsegev/iodine#120]
I tried on Rails Console, and the message didn't publish to WS channel.
But on sidekiq, it is a bit weird. I'm able to publish messages to all clients on sidekiq-scheduler, but when I do `peform_aysnc`, the client didn't receive any message.

Appreciate your help.

**Comment by boazsegev** [comment]
Hi @lucaskuan ,

Thanks for opening the issue... but if to be honest, I am not sure what you are trying to do and where it breaks.

I am fairly certain that the SideKiq process is running in a separate process than the Iodine one, so I don't see how they SideKiq could publish messages to a client (unless using Redis to sync)... an I think that the Rails console runs in a separate processes without running the server (so messages are queued in that process but not delivered).

Am I missing anything?

Cheers,
   Bo.

**Comment by lucaskuan** [comment]
Thanks for answering that.
