### ISSUE TITLE
Ping Pong frame in iodine

### ISSUE THREAD

**Issue by lucaskuan** [boazsegev/iodine#123]
I have a Java WebSocket client built with Java-Webscoket currently experiencing a connection dropping issue that related to weboscket ping/pong. 
According to this https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection it will drop connection when not receiving a pong frame from the server after 90 seconds.
Will iodine send pong frame after receiving ping from the client? If not, how can I do that? I'm on iodine version 0.4.2

**Comment by boazsegev** [comment]
Thanks for the PR! I merged the update and completed the changes. I'll push a patched version soon.
