### ISSUE TITLE
[Rack 3] Response headers with Array value should produce multiple header fields

### ISSUE THREAD

**Issue by taku0** [boazsegev/iodine#131]
### System Information

 - **OS**: Linux 5.15.43
 - **Ruby**:  3.1.2p20
 - **Version**: 0.7.49
 - **OpenSSL**:  OpenSSL 1.1.1q  5 Jul 2022

### Description

[The Rack 3 specification](https://github.com/rack/rack/blob/main/SPEC.rdoc#the-headers-) changes the type of response header with multiple values from newline separated string to array:

> Header values must be either a String instance, or an Array of String instances, such that each String instance must not contain characters below 037.

[CHANGELOG.md](https://github.com/rack/rack/blob/52901caf09ebcda879512a8605059963a49df55d/CHANGELOG.md?plain=1#L29):

> Response header values can be an `Array` to handle multiple values (and no longer supports `\n` encoded headers).

I haven't tried [`isomorfeus-iodine`](https://github.com/isomorfeus/isomorfeus-iodine) yet, but [`for_each_header_data` of `isomorfeus-iodine`](https://github.com/isomorfeus/isomorfeus-iodine/blob/78b981f27ad5823ff117c4a834f10a787f0ead07/ext/iodine/iodine_http.c#L484-L485) still calls `to_s` if the value is not a string.

Maybe we should create an umbrella issue for supporting Rack 3.

### Rack App to Reproduce

```ruby
APP = proc { |env|
  [
    204,
    {
      'set-cookie' => ['aaa=aaa', 'bbb=bbb']
    },
    []
  ]
}
run APP
```

Or using `Rack::Response`:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'

require 'iodine'
require 'rack'

APP = proc { |env|
  response = Rack::Response.new(nil, 204)
  response.set_cookie('aaa', 'aaa')
  response.set_cookie('bbb', 'bbb')
  response.finish
}

Iodine.listen(service: :http, handler: APP)
Iodine.start
```

### Testing code

```sh
curl --include http://localhost:3000/
```

### Expected behavior

```
HTTP/1.1 204 No Content
connection:keep-alive
set-cookie:aaa=aaa
set-cookie:bbb=bbb
content-length:0
date:Sat, 29 Oct 2022 14:43:05 GMT
```

### Actual behavior

```
HTTP/1.1 204 No Content
connection:keep-alive
set-cookie:["aaa=aaa", "bbb=bbb"]
content-length:0
date:Sat, 29 Oct 2022 14:43:05 GMT
```

### Possible fix

If the value is array, call `.join("\n")` in [`for_each_header_data`](https://github.com/boazsegev/iodine/blob/3d6e9bab9cd788f6487024730fa2aa5f20877174/ext/iodine/iodine_http.c#L486-L487).

**Comment by boazsegev** [comment]
Hi @taku0 ,

Thank you for opening this issue 🙏🏻

I'll make time to work on this soon... though I think my solution will probably allow for `\n` in the Strings (for legacy Rack 2.x support) while calling [`for_each_header_data`](https://github.com/boazsegev/iodine/blob/3d6e9bab9cd788f6487024730fa2aa5f20877174/ext/iodine/iodine_http.c#L486-L487) per String in the Array (thus supporting a lax syntax of Rack 3 while preventing Rack 2.x style headers from being broken).

**Comment by taku0** [comment]
Thank you for quick update. It works perfectly.
