### ISSUE TITLE
Iodine.unsubscribe crashes when called with symbol.

### ISSUE THREAD

**Issue by raxoft** [boazsegev/iodine#134]
### System Information

 - **OS**:             Linux 4.15.0
 - **Ruby**:         2.7.6
 - **Version**:     0.7.51
 - **OpenSSL**:  OpenSSL 1.1.1  11 Sep 2018

### Description

Despite the fact that subscribe and publish seem to work with symbols which are also used in examples, calling `Iodine.unsubscribe` with symbol crashes immediately.

### Testing code

```ruby
require 'iodine'
Iodine.unsubscribe(:foo)
```

### Expected behavior

It should not crash.

### Actual behavior

It segfaults. It works only when string is used.

**Comment by boazsegev** [comment]
Hi @raxoft ,

Thank you for opening this issue, as well as PR #133. I'm releasing a fix that I hope would help, it should be up on RubyGems any moment.

Thanks!
   Bo.

**Comment by raxoft** [comment]
Thanks, @boazsegev, for fixing this so quickly. I have found one more issue regarding `:enter_master` event and subscribing, but I didn't have time to craft the standalone example yet. Will post it once I do later this week. Thanks again.

**Comment by raxoft** [comment]
Also, I am not Alexander Pavlenko, but that's ok. :)

**Comment by boazsegev** [comment]
Hi Patrick,

Thank you for opening these issues and helping improve iodine. I'm sorry about the copy and paste errors both in the code and the credit you deserve in the changeling (both, hopefully, are now fixed).

And you're welcome.

B.
