### ISSUE TITLE
Writes to STDOUT even when Iodine.verbosity = 0

### ISSUE THREAD

**Issue by jsaak** [boazsegev/iodine#139]
Writes to STDOUT even when Iodine.verbosity = 0

**Comment by boazsegev** [comment]
Hi @jsaak 

Thank you for reporting this issue.

I am assuming you are using the CLI to set `Iodine.verbosity` (using `-V 0`)?

Using the function `Iodine.verbosity` I cannot reproduce the issue, however when using the CLI I saw that the value validation introduced a bug.

For now I recommend using `Iodine.verbosity = 1` (only fatal errors will be printed). I hope to fix this issue for the next version.

Kindly,
  Bo.
