### ISSUE TITLE
The Fixnum is gone as of Ruby-2.4

### ISSUE THREAD

**Issue by zblsv** [boazsegev/iodine#143]
https://github.com/boazsegev/iodine/blob/e5560c5455a00a5d58acc3b690536191c8e19893/ext/iodine/iodine_defer.c#LL270C3-L270C40

It seems to me that this check cannot be passed. On Ruby-3.2.2 I have `milliseconds must be a number. (TypeError)` when I call `Iodine.run-every milliseconds: 15000`.

**Comment by zblsv** [comment]
Sorry, according to https://github.com/ruby/ruby/blob/cc68d692f80bde4336bbefa2c0872f2a63064edb/doc/extension.rdoc T_FIXNUM is not gone despite of Fixnum is gone.

**Comment by janbiedermann** [comment]
milliseconds is not a kwarg, just the first arg:
`Iodine.run-every 15000`

**Comment by zblsv** [comment]
Yes, I realized my mistake, thank you.
`Iodine.run_every(15000, 5) { pp Time.now }`
