### ISSUE TITLE
workers / threads available 

### ISSUE THREAD

**Issue by madsheep** [boazsegev/iodine#15]
Hi,

This is more of a question than a real issue - I'm running iodine and using it to serve many websockets. In my dev env I've noticed that even if I set processes and threads to 1 (confirmed by iodine output: `Running 1 processes X 1 threads`) I can still connect more than one websocket to the server. How come? Isn't there a direct correlation between number of threads and number of websockets I can connect?

**Comment by boazsegev** [comment]
Hi @madsheep ,

I'm happy to read that you're enjoying iodine. and utilizing one of it's bigger strengths - it's native websocket support.

Iodine is an evened server, similar in it's architecture to `nginx` and `puma`. It's different than the simple "thread-per-client" design that is often taught when we begin to learn about network programming.

By leveraging `epoll` (on Linux) and `kqueue` (on BSD), iodine can listen to multiple network events on multiple sockets using a single thread.

All these events go into a task queue, together with the application events and any user generated tasks (suck as ones scheduled by [`Iodine.run`](http://www.rubydoc.info/github/boazsegev/iodine/Iodine#run-class_method).

In pseudo-code, this might look like this

```ruby
QUEUE = Queue.new

def server_cycle
    QUEUE << get_next_32_socket_events # these events schedule the proper user code to run
    QUEUE << [server]
end

def run_server
      while ((event = QUEUE.pop))
            event.shift.call(*event)
      end
end
```

In pure Ruby (without using C extensions or Java), you can do the same by using `select`, which has some issues but works well for smaller concurrency levels (up to 1K sockets or so).

The server events are fairly fast and fragmented (longer code is fragmented across multiple events).

The thread pool is mostly there to manage slow user code. If your application's code is slower or requires external resources (i.e., uses databases or a pub/sub service such as Redis), than your application will "starve" the server (that is patiently waiting to run it's tasks on the same thread).

The slower your application code, the more threads you will need to keep the server running smoothly.

I hope his answers your question. If you need anymore help or have any more questions please feel free to ask :-)

Have an amazing day!
Bo.

**Comment by madsheep** [comment]
This is awesome - better than I expected. Thanks for the detailed explanation - would suggest making this part of the readme, I didn't understand the design before.

![](http://i.imgur.com/vUJBo79.gif)

**Comment by boazsegev** [comment]
Thanks for the idea, your question now changed the readme and will forever echo in the Github space :-)
