### ISSUE TITLE
rage-rb

### ISSUE THREAD

**Issue by rsamoilov** [boazsegev/iodine#151]
Hi @boazsegev ,

I wanted to let you know that for the last few months, I've been working on [a framework](https://github.com/rage-rb/rage) based on Iodine. The framework attempts to fix some of the issues I see as Rails' core flaws. Feel free to check it out and share your feedback.

On a side note, I just wanted to say I think you're an absolute legend 💪. Iodine is one of the best Ruby libraries out there, and I'm looking forward to the time when the community recognizes your work the way it deserves. Keep it up!

**Comment by boazsegev** [comment]
Hi @rsamoilov ,

Thank you for your kind words! I'll have a look as soon as I have some time to play around, I hope it will be soon as I'm excited to see how you handle the transition between threads and fibers.

FYI: it might take a long time, but I've started to work on iodine 8.x. I'm also attempting to design [an alternative to the CGI Rack protocol](https://github.com/boazsegev/neorack) that will allow you to control the response object and possibly support non-synchronous responses. If there are any specific features you need, I would love to know.

Thank you kindly,
   B.
