### ISSUE TITLE
Logger is not showing.. sometimes :(

### ISSUE THREAD

**Issue by lucaskuan** [boazsegev/iodine#30]
My Rails application that use Iodine is set to log with STDOUT
`config.logger = ActiveSupport::Logger.new(STDOUT)`
But I found whenever I use `puts` nothing is showing to my terminal until the next server restart.
It is because my bad config on the Iodine?

**Comment by boazsegev** [comment]
Hi @lucaskuan ,

Did my answer resolve your issue?

**Comment by lucaskuan** [comment]
Hi @boazsegev, thank you for your quick and detail response. I haven't have a chance to deep dive into this situation these days. I agree with your point that system STDOUT delays the output, I will come back to this issue later and let you know how to recreate that.
