### ISSUE TITLE
Error with ActionCable 5.2.0

### ISSUE THREAD

**Issue by mdesantis** [boazsegev/iodine#38]
Hello,

I don't know whether this project support Rails or not, but I guess it does since Rails is a Rack application :-) anyway, I have the following error:

```
#<Thread:0x00007fd6d6758cd0@/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:75 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:75:in `block (2 levels) in spawn'
	4: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:86:in `run'
	3: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:86:in `loop'
	2: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:93:in `block in run'
	1: from /home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:41:in `block in detach'
/home/user/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.0/lib/action_cable/connection/stream_event_loop.rb:41:in `close': Bad file descriptor (Errno::EBADF)
```

It happens on a newly created Rails 5.2.0 application, Ruby 2.5.1, iodine 0.6.3, visiting any page which includes an ActionCable socket. It can be reproduced with the following steps:

1. Create a new Rails 5.2.0
2. Generate a scaffold (just in order to have a page to visit)
3. Add iodine to Gemfile
4. Run `bundle exec iodine -p 3000 -t 8 -w 1 -www public -v`
5. Visit the scaffold page from the browser in order to make it try to connect to ActionCable websocket

**Comment by boazsegev** [comment]
Hi @mdesantis ,

Thank you for opening this issue 🙏🏻👍🏻

I have no idea what might cause the issue, as iodine follows the Rack specifications. I will try to replicate the issue this weekend and solve it.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
@mdesantis ,

Thank you for exposing this issue.

The exceptions were raised because the status code reported by ActiveCable was negative (`-1`), which iodine recognized as an abnormal status code, resulting is the connection being disconnected.

I fixed it so negative status codes would be ignored for hijacking and upgrading purposes.

Please upgrade to version 0.6.4 and enjoy the fix.

If you have any further issues, please let me know.

Thanks again 🙏🏻🙏🏻👍🏻
Bo.

**Comment by mdesantis** [comment]
Wow, it was so fast O.o I confirm that it works now!

**Comment by boazsegev** [comment]
@mdesantis , thank you for keeping me posted.

I'm happy I could help :-)
