### ISSUE TITLE
Thread safety issue?

### ISSUE THREAD

**Issue by ojab** [boazsegev/iodine#44]
I'm not quite sure that it's iodine issue, but I suspect so:
```ruby
require 'iodine'
require 'net/http'
require 'concurrent'

class ServerTest # :nodoc:
  def self.logs
    @logs ||= Concurrent::Array.new
  end
end

class App # :nodoc:
  def call(_env)
    ServerTest.logs << 'log'
  end
end

Thread.new do
  Iodine::Rack.run(
    App.new,
    Port: '3099', Address: '127.0.0.1'
  )
end

Net::HTTP.get(URI('http://127.0.0.1:3099'))

p ServerTest.logs
# => []
```

the same test with puma shows expected `["log"]`

**Comment by ojab** [comment]
Fedora-29 x86_64 here & iodine-0.7.7

**Comment by boazsegev** [comment]
I think this is a cluster mode issue... iodine's default is cluster mode whereas Puma's default is a single process.

It should work fine by adding `Iodine.workers = 1` before starting iodine. 

If I understand correctly, the `Concurrent::Array.new` is unique to each process. It might be **thread** safe, but it isn't shared across **process** boundaries.

Do you experience something similar when using Puma with workers?

As for logging, it's easy to capture iodine logs to a file (when using `iodine -v` or setting [`Iodine::DEFAULT_HTTP_ARGS[:log] = true`](https://www.rubydoc.info/github/boazsegev/iodine/master/Iodine%2Elisten2http)) by piping the STDERR output to a file. i.e.:

```bash
$ iodine -v -w 1 -t -1 2> my_log.log
```

Another option, if you want everything in an Array, is to use the pub/sub extensions:

```c
require 'iodine'
require 'net/http'
require 'concurrent'

class ServerTest # :nodoc:
  def self.logs
    @logs ||= Concurrent::Array.new
  end
end

Iodine.subscribe(:log) do |ch, msg|
  ServerTest.logs << msg
end

# puts "subscribed"

class App # :nodoc:
  def call(_env)
    Iodine.publish :log, "log this"
    nil
  end
end

ROOT_PID = Process.pid

# perform the HTTP request after the server starts the event loop
Iodine.defer do
  if ROOT_PID == Process.pid
    # perform in new thread, to avoid deadlock when iodine is single threaded and single process
    Thread.new() { Net::HTTP.get(URI('http://127.0.0.1:3099')) }
  end
end

Iodine::Rack.run(
  App.new,
  Port: '3099', Address: '127.0.0.1'
)

p ServerTest.logs
```

I hope this helps.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
P.S.

Iodine's pub/sub extensions publish messages across machine process (and machine) boundaries.

This would allow all the logs from all the machines to be sent to a single machine (i.e., when syncing through [Redis](https://www.rubydoc.info/github/boazsegev/iodine/master/Iodine/PubSub/Redis)).

I'm not sure this is what you wanted, but it will solve the cluster mode concern.

**Comment by ojab** [comment]
Ah, thanks a lot! I'm new to Iodine and haven't counted for multiprocess by default. Works find with `Iodine.workers = 1`.
