### ISSUE TITLE
PubSub introspection

### ISSUE THREAD

**Issue by ojab** [boazsegev/iodine#47]
Right now PubSub is very opaque, is there any way for introspection?
For example https://github.com/palkan/litecable needs a method to teardown channel (i. e. unsubscribe all clients), is there any way to implement it using iodine pubsub?

**Comment by boazsegev** [comment]
Not yet, but I can probably find a way around it... at least partially... but I'm not sure I understand what you want.

Could you describe what subscription properties you would like to be able to view and/or manipulate? Also, how would you expect this to behave in a multi-machine scenario (assume we have many iodine servers running together, syncing pub/sub using Redis in the backend)?

Does the "unsubscribe all clients" feature work only for a single machine, only for a single process, or does it unsubscribe everyone in every machine (when syncing using Redis)? What's the use case?

I don't think I can easily force clients to unsubscribe, but I think I can easily mute a subscription or a channel on a specific process, if the need arises (I might not be able to un-mute it though, I'll have to look into that). Is that what you want?

Is it part of a hot-restart use-case (if so, all clients will be unsubscribed and disconnected gracefully during iodine's existing hot-restart)?

**Comment by ojab** [comment]
After some investigation I've found that I can't really explain what exactly is needed yet ._.
Closing for now.
