### ISSUE TITLE
Callback handler class is used directly without creating a new instance

### ISSUE THREAD

**Issue by ojab** [boazsegev/iodine#48]
Websocket spec says that `If the callback handler is a Class object, the server will create a new instance of that class.`, but according to:
```ruby
require 'iodine'
require 'websocket-client-simple'

class ClientSocket # :nodoc:
  def self.on_open(client)
    p client
  end
end

class App # :nodoc:
  def call(env)
    unless env['rack.upgrade?'] == :websocket
      return [404, { 'Content-Type' => 'text/plain' }, ['Not Found']]
    end

    env['rack.upgrade'] = ClientSocket

    [0, {}, []]
  end
end

Thread.new do
  Iodine::Rack.run(
    App.new,
    Port: '3099', Address: '127.0.0.1'
  )
end

WebSocket::Client::Simple.connect('ws://127.0.0.1:3099')
```
new instance is not created and `ClientSocket.on_open` is called (iodine-0.7.7).

**Comment by boazsegev** [comment]
Yes, you are correct.

This was discussed somewhere during [this discussion](https://github.com/rack/rack/pull/1272), and it was decided that a static module approach should be made available, allowing some implementations to minimize the number of objects created.

I should update the specification. whatever is passed along to the `env['rack.upgrade?']` will be assumed to be the callback object (even a module / class).
