### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [boazsegev/iodine#50]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “free_ws_buffer”](https://github.com/boazsegev/iodine/blob/1fb4d298cb764098b811f5f8c46b33004a9e4529/ext/iodine/websockets.c#L88 "Update candidate").

**Comment by boazsegev** [comment]
That's a fair point.

I'm pretty inconsistent about this. I always wonder if the extra `if` test might save me a function call (and how often).

On the other hand, such micro optimizations are probably a waste of time and readability should be my higher concern.

Thanks! I'll fix this in the facil.io repo.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/boazsegev/facil.io/commit/f084039a12c6a4ac36f883060d27131a9306532d "Deletion of a redundant check").
