### ISSUE TITLE
Documentation: config/iodine.rb

### ISSUE THREAD

**Issue by giovannibonetti** [boazsegev/iodine#51]
First of all, thank you for this amazing project! 😀

I was reading the docs section [Running with Rails](https://github.com/boazsegev/iodine#running-with-rails) and then I got confused in this part:

> Optionally, it's possible to add a config/iodine.rb file

I wonder how should I tell Iodine to load `config/iodine.rb`.
I looked up the command line options and I expected to find a flag like Puma's:
```sh
bundle exec puma -C config/puma.rb
```

1) Is there a flag I can pass to Iodine to load `config/iodine.rb`? Something like this:
```sh
bundle exec iodine -C config/iodine.rb
```

2) Does it work when I call it with `rails s` instead?

**Comment by boazsegev** [comment]
Hi @giovannibonetti ,

Thank you for opening this issue!

You are right, I confused the folder name. The `iodine.rb` file should be placed in the `config/initializers` folder, so it is automatically loaded during Rails initialization.

I fixed the documentation to reflect this. 

I'm traveling right now, so it takes me a while to respond. But if you have any further questions, please feel free to ask and I will answer as soon as I can.

Kindly,
   Bo.

**Comment by giovannibonetti** [comment]
Thank you for the quick response! 😀
