### ISSUE TITLE
BIO_up_ref: symbol not found (docker)

### ISSUE THREAD

**Issue by Shelvak** [boazsegev/iodine#55]
Hi there, I'm trying to test iodine in my env, and I'm having problems in docker (my prod env). Any thoughts in what could I do about that, or if i need to install any extra lib?

Tested in => CodeFresh && locally with `Docker version 18.09.0-ce, build 4d60db472b`
Alpine => 3.7
Ruby => 2.5.3
iodine => (0.7.21)
```
Step 16/24 : RUN bundle exec rails assets:precompile
 ---> Running in 432016e7bd79
rails aborted!
LoadError: Error relocating /usr/src/app/vendor/bundle/ruby/2.5.0/gems/iodine-0.7.21/lib/iodine/iodine.so: BIO_up_ref: symbol not found - /usr/src/app/vendor/bundle/ruby/2.5.0/gems/iodine-0.7.21/lib/iodine/iodine.so
[0m[91m/usr/src/app/vendor/bundle/ruby/2.5.0/gems/iodine-0.7.21/lib/iodine.rb:5:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/iodine-0.7.21/lib/iodine.rb:5:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
/usr/local/bundle/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
/usr/src/app/config/application.rb:11:in `<top (required)>'
/usr/src/app/Rakefile:4:in `require'
/usr/src/app/Rakefile:4:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
Removing intermediate container 432016e7bd79
The command '/bin/sh -c bundle exec rails assets:precompile' returned a non-zero code: 1
[SYSTEM] Error: Failed to build image: caused by NonZeroExitCodeError: Container    for step title: Building Docker Image, step type: build, operation: Building image failed with exit code: 1
```
I tried to start up the server instead of the precompile and getting the same error.

If you need any extra data just tell me :+1:

**Comment by Shelvak** [comment]
You can close this issue,  because I figured it out that I need openssl1.1 either use TLS or not...
My positive tests to startup iodine:
- NO_SSL=true bundle install # I saw that in the extensions.rb part
- Start the Dockerfile with alpine-3.9 and install openssl (1.1.1a)

It'ld be super helpfully if you add in the readme that we need openssl1.1 independently of the use of TLS. 

Cheers :+1:

**Comment by boazsegev** [comment]
Hi @Shelvak , 

Thank you for opening this issue!

This might be a bug in the [OpenSSL detection code](https://github.com/boazsegev/iodine/blob/e40f70ad6b985619caad5728ad6372d2f0029796/ext/iodine/extconf.rb#L34-L50). I'm not sure why, but the installer recognized a matching OpenSSL version installed on your machine.

I don't really use Docker, so I'm not sure how that happened.

Do you know which OpenSSL version you have installed or if LibreSSL is installed (and which version)?

Kindly,
   Bo.

**Comment by Shelvak** [comment]
yeah I tried with 
- libssl1.0.2q-r0 (just for dependency of other things) => not work 
- openssl 1.0.2q-r0 => not work
- libressl 2.6.5-r0 (tried after your answer) => not work

All the tests were installing (or not) the packages before the `bundle install` 

And iodine works with both libressl(2.7.4) and openssl(1.1.1a) in alpine3.9.

If you tell me how can I do to get the `puts` output in the extconf.rb (because bundle --verbose doesn't show it) I can provide more context.

If you want to try with docker, you can add this to a Dockerfile in your repo and then test with `docker build -t tmp . && docker run -it tmp bash` and then `rails c` and check if that works.
```docker
FROM ruby:2.5.3-alpine3.7  # If you then change this line to `alpine3.9` you will see that with openssl1.1 works

# Patch to get global bins
ENV BUNDLE_BIN="$GEM_HOME/bin"
ENV PATH $BUNDLE_BIN:$PATH
RUN mkdir -p "$BUNDLE_BIN"
RUN chmod 777 "$BUNDLE_BIN"

RUN echo "gem: --no-rdoc --no-ri" >> ~/.gemrc \
    && apk --update add --virtual build-dependencies build-base \
    && apk --update add libpq bash nodejs libxml2 libxml2-dev libxml2-utils libxslt \
                        zlib tzdata git openssh file  \
    && gem install bundler 

WORKDIR /tmp

COPY Gemfile Gemfile.lock ./

RUN apk --update add openssl

RUN bundle install --deployment --jobs 5 

ADD . ./

EXPOSE 3000

CMD rails server
```

**Comment by boazsegev** [comment]
I'll look into this a bit more when I have a decent internet connection. I'm currently in a jungle retreat in Costa Rica, where a VM download might take a couple of days.

Thanks again!

I'll keep you posted.
