### ISSUE TITLE
Iodine refusing to log anything because it's too long

### ISSUE THREAD

**Issue by weskerfoot** [boazsegev/iodine#56]
I'm seeing messages like the following:
`ERROR: log line output too long (can't write).ERROR:`

I believe this is because of this issue:
https://github.com/boazsegev/iodine/blob/d63402b15b7cd68e4be55ad3d67372a74cfe3191/ext/iodine/fio.h#L184

Any plans to make this allocate on the heap instead? Logging is broken for me in this case (with the hard limit).

If it's too tricky to make it allocate space on the heap when the log entry is too long, then maybe a separate macro for "verbose logging" or something would work?

**Comment by boazsegev** [comment]
Hi @weskerfoot ,

Thank you for opening this issue.

Which version of iodine are you running?

This issue was fixed a while back, where [the error message is printed](https://github.com/boazsegev/iodine/blob/d63402b15b7cd68e4be55ad3d67372a74cfe3191/ext/iodine/fio.h#L432-L443), albeit in a truncated form... In fact, reading the code I suspect it might be written twice... I need to revisit that.

Kindly,
  Bo.

**Comment by weskerfoot** [comment]
@boazsegev Ah, I'm running 0.7.16. so that may be the issue then. I will try upgrading and see if that solves the issue. Thanks!

**Comment by ianks** [comment]
Im getting the same issue

**Comment by adam12** [comment]
> This issue was fixed a while back, where [the error message is printed](https://github.com/boazsegev/iodine/blob/d63402b15b7cd68e4be55ad3d67372a74cfe3191/ext/iodine/fio.h#L432-L443), albeit in a truncated form... In fact, reading the code I suspect it might be written twice...

I was able to confirm what's broken on 0.7.16 (no output) is working on 0.7.22 (truncated output), albeit with the error output twice as you expected.

**Comment by boazsegev** [comment]
Thank you @weskerfoot and @adam12 !

I got fixed the double logging issue for iodine 0.7.23. I'll release an update later today or tomorrow. I also made the truncation message clearer.

Thanks for opening the issue and for the updates!
   Bo.
