### ISSUE TITLE
SSL/TLS crashes with "No supported SSL/TLS library available"

### ISSUE THREAD

**Issue by Davidzhu001** [boazsegev/iodine#58]
Hey GitHub Friends,

First at all, I really appreciate about your contributions on GitHub about networks.

I want to ask you a question which stacked me for a while about how to connect signalr client with ruby.

```
   require 'iodine'
	
   class EchoClient

   def on_open(connection)
    @messages = [ "Hello World!",
      "I'm alive and sending messages",
      "I also receive messages",
      "now that we all know this...",
      "I can stop.",
      "Goodbye." ]
    send_one_message(connection)
   end

   def boxConnStateChanged(connection, message)
    puts "Received: #{message}"
    send_one_message(connection)
   end

  def box_conn_ctate_changed(connection, message)
    puts "Received: #{message}"
    send_one_message(connection)
  end

 end


    url = "http://fbcs101.fbox360.com/push?at=#{@access_token}&cid=#{@xFboxClientId}"
    Iodine.threads = 1
    tls = Iodine::TLS.new
    Iodine.connect url: url, handler: EchoClient.new, ping: 40, service: :tls, tls: tls
    Iodine.start
````

here are some errors i got 

`
FATAL: No supported SSL/TLS library available.
`

**Comment by boazsegev** [comment]
Hi @Davidzhu001 

Which version of OpenSSL and iodine are you using?

Make sure to install OpenSSL 1.1.1 or later before installing the latest version of iodine.

As indicated in the readme file, [OpenSSL > 1.1.0 is required for TLS connections](https://github.com/boazsegev/iodine#tls-12-support).

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Side-note:

For WebSocket connections, please use `Iodine.connect "ws://..."` or `Iodine.connect "wss://...`.

The `http` schema should be reserved for future client support for HTTP connections.

**Comment by Davidzhu001** [comment]
@boazsegev thanks so much for your help!  so now signalr is not really supported ? right?

**Comment by boazsegev** [comment]
@Davidzhu001 ,

Iodine does not provide special support for the SignalR protocol, but it's possible to connect to signalR with iodine. I'm not sure what special support signalR might require.

A WebSocket TLS connection is possible when installing the latest OpenSSL / LibreSSL libraries before installing iodine.

This is basically all signalR needs. Once you have the open WebSocket connection, you will need to manage the signalR protocol within the WebSocket callbacks, [as detailed here](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md).

Kindly,
   Bo.

**Comment by Davidzhu001** [comment]
![image](https://user-images.githubusercontent.com/9436230/52567718-e6b9c200-2e47-11e9-95d0-08174d46206a.png)
did i do anything wrong?

**Comment by Davidzhu001** [comment]
@boazsegev thanks so much! Friend

**Comment by adam12** [comment]
@Davidzhu001 Your code looks fine. I suspect Iodine didn't detect your recent OpenSSL version, especially if it ended up in `/usr/local`.

If you clone the Iodine project and try building the makefile locally, does it detect OpenSSL?

```
$ git clone https://github.com/boazsegev/iodine
$ cd iodine/ext/iodine
$ ruby extconf.rb
```

Should see something like this:
```
checking for kevent()... yes
checking for clang... yes
testing clang for stdatomic support...
using clang compiler v. 4.2.1
.
checking for -lcrypto... yes
checking for -lssl... yes
Detected OpenSSL library, testing for version.
Confirmed OpenSSL to be version 1.1.0 or above (OpenSSL 1.0.2q  20 Nov 2018)...
* Compiling with HAVE_OPENSSL.
creating Makefile
```

**Comment by boazsegev** [comment]
@Davidzhu001 ,

Did @adam12 's answer solve your issue?

@adam12 - thanks!

B.

**Comment by Davidzhu001** [comment]
`

checking for kevent()... yes
checking for clang... yes
testing clang for stdatomic support...
using clang compiler v. 4.2.1
.
checking for -lcrypto... yes
checking for -lssl... yes
Detected OpenSSL library, testing for version.
FAILED: OpenSSL version not supported (OpenSSL 1.0.2q  20 Nov 2018 is too old).
creating Makefile
`
it seems it didn't. so what should i do then

**Comment by boazsegev** [comment]
@Davidzhu001 ,

Iodine will try to link against the OpenSSL that Ruby links against, using the header files provided by the Ruby path resolution.

It seems that Ruby is linking against OpenSSL version 1.0.2q. I would recommend reinstalling Ruby with the latest OpenSSL patch (it probably isn't just iodine's security, it's the whole application's security).

Alternatively, you could override these options by [configuring bundler, as mentioned here](https://github.com/puma/puma/issues/783#issuecomment-154142017) (the solution was provided for Puma installations) - remember to use the correct openssl path:

```bash
bundle config build.iodine --with-opt-dir=/usr/local/opt/openssl
gem install iodine -f -V
```

Please let me know if this helps.

**Comment by Davidzhu001** [comment]
@boazsegev @adam12  thanks so much guys, the problem of TLS solved.
still struggle with how to make signalr work with iodine!
Thank you

**Comment by boazsegev** [comment]
@Davidzhu001 ,

Good luck with authoring a SignalR client protocol 👍🏻

The specification looks a little complicated and difficult to read. Also, it looks almost binary in nature (like [adding the `0x1E` byte after each JSON encoded message](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#json-encoding) or the [MsgPack encoding](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#messagepack-msgpack-encoding))... I hope you work it out. Maybe you'll end up with a gem that will parse / format SignalR messages ☺️

Kindly,
   Bo.
