### ISSUE TITLE
Errno::EPIPE: Broken pipe @ io_writev - <STDOUT>

### ISSUE THREAD

**Issue by sshock** [boazsegev/iodine#63]
After updating iodine to 0.7.25, I am now seeing a broken pipe error during rails shutdown.

It's trying to do a `puts "Exiting"`, but stdout is no longer available??

The call stack looks like this:

```
[GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `write`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `puts`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `puts`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `ensure in start`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `start`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147 :in `block in perform`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142 :in `tap`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142 :in `perform`
 [GEM_ROOT]/gems/thor-0.20.3/lib/thor/command.rb:27 :in `run`
 [GEM_ROOT]/gems/thor-0.20.3/lib/thor/invocation.rb:126 :in `invoke_command`
 [GEM_ROOT]/gems/thor-0.20.3/lib/thor.rb:387 :in `dispatch`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/command/base.rb:65 :in `perform`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/command.rb:46 :in `invoke`
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands.rb:18 :in `<main>`
 [GEM_ROOT]/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21 :in `require`
 [GEM_ROOT]/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21 :in `block in require_with_bootsnap_lfi`
 [GEM_ROOT]/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83 :in `register`
 [GEM_ROOT]/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20 :in `require_with_bootsnap_lfi`
 [GEM_ROOT]/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29 :in `require`
 [GEM_ROOT]/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291 :in `block in require`
 [GEM_ROOT]/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257 :in `load_dependency`
 [GEM_ROOT]/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291 :in `require`
bin/rails:4 :in `<main>`
```

The nested exception is:
```
Errno::EPIPE: Broken pipe @ io_writev - <STDOUT>
 [GEM_ROOT]/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:57 :in `write`
 SystemExit: exit
 [GEM_ROOT]/gems/rack-2.0.6/lib/rack/server.rb:293 :in `exit`
```

One weird thing is, that looks like an INT handler, but I'm pretty sure we are stopping rails with a TERM signal not INT, so not sure if that is a clue or not.

**Comment by boazsegev** [comment]
Thank you for opening this issue.

I'm trying to find out why you're experiencing this issue... But I can't reproduce it.

Iodine simply allows signals to pass through, so I'm not even sure this is an iodine issue. Do you have an example application I can copy to reproduce the issue?

Kindly,
  Bo,

**Comment by sshock** [comment]
Hi Bo.  I'll try to put together a sample application sometime.  In the meantime, here is a summary of how things are set up that may help to reproduce it:

1. We're using iodine via Plezi middleware.  I.e., we run the rails server and we have `config.middleware.use Plezi` in our config/application.rb.

2. We're running rails inside of foreman.  I.e., we run `foreman start` and have `rails: ./bin/rails s` in our Procfile, along with sidekiq and another process we run.

3. We are running foreman from a systemd service on LInux.

4. I'm not able to reproduce this problem when just killing the foreman or rails process.  I'm only able to reproduce it during a deploy with capistrano, which restarts the service.  The restart process calls a stop script that kills rails (and sidekiq) with a TERM signal and then starts everything back up running `foreman start`.

**Comment by boazsegev** [comment]
Side-Note:

The error is probably a result of the fix implemented for issue #59 .

`SIGPIPE` is often captured by servers and ignored, since it's raised by sockets that experience abrupt disconnections (which is very common for web servers).

Where iodine, before, would stop signals from reaching any Ruby signal handlers, [now the signals propagate "upwards" to whatever signal handler might have been set previously](https://github.com/boazsegev/iodine/blob/81635737298599d84c9c56c7d14ef969ee8650ea/lib/iodine.rb#L133-L149).

The error might have existed previously but had been masked by iodine (or Puma) setting signal handlers to ignore `SIGPIPE`.

You can try adding this line of code to the Rails application and see if the error message goes away (which would indicate the error was probably previously masked):

```ruby
Signal.trap("SIGPIPE", "IGNORE)
```

**Comment by sshock** [comment]
Ah, I see.  Yeah, that makes sense.  Thanks for your help.  I'll give that a try and/or just have HB ignore that error since it doesn't seem to actually hurt anything.

Thanks for looking into this for me.  You can go ahead and close this issue now.

**Comment by boazsegev** [comment]
Let me know if you need anything 👍🏻
