### ISSUE TITLE
Iodine doesn't pass external SCRIPT_NAME env variable

### ISSUE THREAD

**Issue by thexa4** [boazsegev/iodine#68]
We want to switch to Iodine for a rails app that is behind a reverse proxy. The app is mounted on a subfolder of the domain using nginx so we use the `SCRIPT_NAME` environment variable to make the url helpers return the correct urls.

When using Iodine to serve the app it seems that the `SCRIPT_NAME` variable is set to `""` instead of using the value supplied from the system. From what I could find it seems to happen here: https://github.com/boazsegev/iodine/blob/67b08bee0f419280b39fa3a5df7aedb917c02e03/ext/iodine/iodine_http.c#L837
This causes the url helpers to create incorrect urls.

Is there a way to configure iodine to use a different `SCRIPT_NAME` or make it use the system supplied value?

**Comment by boazsegev** [comment]
@thexa4 ,

Thank you for opening this issue ☺️🙏🏻

I'd be happy to make any change that will improve iodine's compatibility with Rack and Puma.

In this case, I believe that the behavior of incorporating the global `ENV` value for `SCRIPT_NAME` into the HTTP request's `env` is a [Puma specific extension](https://github.com/puma/puma/blob/698979fd6f526833dadfacd2c0586655528566f9/lib/puma/binder.rb#L28) or perhaps a convention I wasn't aware of.

As far as I understand, the `SCRIPT_NAME` variable in the HTTP request should be set by the application server when the application server supports more than a single application using a URL prefix of sorts.

This is what is says in the specification:

> `SCRIPT_NAME`
>
> The initial portion of the request URL's “path” that corresponds to the application object, so that the application knows its virtual “location”. This may be an empty string, **if the application corresponds to the “root” of the server**.

Then again, I really don't mind adopting Puma's approach.

I'll try to get to it this week.

Kindly,
   Bo.

P.S.

**Side-note**:

From your description I understand that `SCRIPT_NAME` is a static global variable that is process bound - each process will have a static, constant, value for this variable (this is the nature of environment variables).

I would recommend to test the value once during initialization and caching the result as a boolean flag.

Testing this value each request means that the String `SCRIPT_NAME` needs to be hashed and a potentially expensive lookup in the hash needs to be performed for each request. These operations could be optimized away.

**Comment by boazsegev** [comment]
I pushed a patch and will probably release it tonight (UTC time).

Just a head's up: 

`SCRIPT_NAME` will be empty if set to the root URL `/`.

I chose this approach since the root URL `/` isn't really a valid `SCRIPT_NAME` value (there's no initial portion prior to the path) - i.e., concatenation might produce the unexpected path `//`.

If you think this is a mistake, please let me know.

**Comment by thexa4** [comment]
Wow, that's quick!
Yes, I think setting `SCRIPT_NAME` to empty when it's a `/` isn't that big of a problem. Might be confusing that your environment variable sometimes changes but shouldn't have any impact.

Thanks for fixing this.

**Comment by boazsegev** [comment]
Patch released 🎉

Thanks again for opening the issue 🙏🏻👍🏻
