### ISSUE TITLE
Pidfile optional argument for server

### ISSUE THREAD

**Issue by Shelvak** [boazsegev/iodine#72]
Hi there, something useful to have is the pidfile argument to can kill the main process.

I'm currently using `rails server --pid /my.pid` but the problem with that is that the port and the bind/socket in the iodine initializer is ignored, and I have to put all the settings in the rails server command (`rails s -b /socket -p 0 --pid /my.pid`) instead of just `iodine` =) .

Thanks in advance.

**Comment by boazsegev** [comment]
@Shelvak ,

Thank you for opening this feature request.

I assume you're looking to a feature that will act the same as Puma's `--pidfile` command line option - only listing the root process's `pid` number, not any of the worker processes...?

Please let me know if there's anything else you might need or desire from this feature.

In the meantime, here's a code-based approach you could use in your iodine application. In this approach, the `pid` file name is hard-coded:

```ruby
Iodine.on_state(:pre_start) do
  IO.binwrite("iodine.pid", "#{Process.pid}\r\n")
end

Iodine.on_state(:on_finish) do
  File.delete("iodine.pid")
end
```

**Comment by Shelvak** [comment]
Thank you so much. Yeah I migrated my app from puma to iodine, (because of the memory leak mainly haha).

But independently of the webserver, I use the pidfile (specially with docker) because I prefer a _soft_ app kill when I stop the docker container. And for that I need the pidfile =)

Thanks for the fast response and feature.
