### ISSUE TITLE
Iodine with sleep high cpu consumption from Nginx

### ISSUE THREAD

**Issue by Shelvak** [boazsegev/iodine#75]
Hi there, me again. 

I'm getting high CPU consumption with sleep's (in ruby and via exec command in bash), but only when I use nginx as a proxy server.

If I hit the same url without nginx, directly to the port it doesn't happen (the CPU is really slow hitting directly).

I've tried with port (3005) and with Unix Socket file, and it's the same result.

I've tried with the next script (in a controller action):
```ruby
    Benchmark.bm do |bm|
      bm.report(:sleep_2) { sleep 2 }
    end
```
Results:
With nginx:
```
                        user        system      total        real
sleep_2  1.567849   0.136582   1.704431 (  2.000030)
```
Without nginx:
```
                        user        system      total        real
sleep_2  0.001163   0.000095   0.001258 (  2.000112)
```

I ran the server with strace and the next files are the result (between the GET request and the write of "sleep2" (or `comandaso`) in the log. Hope that is useful for you. I attached the nginx config too, if you see that I have to add any line let me know.

[without_nginx.txt](https://github.com/boazsegev/iodine/files/3224868/without_nginx.txt)
[with_nginx.txt](https://github.com/boazsegev/iodine/files/3224869/with_nginx.txt)
[nginx.txt](https://github.com/boazsegev/iodine/files/3224875/nginx.txt)

Parsed calls count with call names:
```
    Method name Without  with
     epoll_wait  11091     12
         ENOENT    405     52
      nanosleep    227    513
         ENOTTY     65      1
        resumed     43      8
         EINVAL     20      3
            brk     49     50
       mprotect    842    857
              p      5       
          EBADF      5       
          opost     16       
          ppoll     13     14
    sched_yield      5      6
          futex     33     35
         EAGAIN     33     10
              r      2       
             08      1       
             rw      1       
    EINPROGRESS      1       
       recvfrom     60     57
         select     15     12
          EINTR             1
```

Ruby: 2.5.5 && 2.6.3
Rails: 5.2.3
Nginx: 1.16.0-1 (native && with OpenResty 1.13.6.2)

If you need any other data let me know.
Thanks in advance.

**Comment by boazsegev** [comment]
Hi @Shelvak ,

Thank you for opening this issue.

I didn't get to recreate the issue. To recreate the issue I'm missing just two more detail:

1. What are iodine's runtime settings (threads / workers)?

1. how are you "stressing" the server? Are you using an HTTP benchmarking tool to to send requests out to iodine (i.e., `wrk`)? If so, what is the benchmarking tool's concurrency level / settings?

A review of [the the Ruby code](https://github.com/ruby/ruby/blob/d48783bb0236db505fe1205d1d9822309de53a36/process.c#L7368-L7381) and [the Benchmark module code](https://github.com/ruby/ruby/blob/d48783bb0236db505fe1205d1d9822309de53a36/lib/benchmark.rb#L274-L301), show that they collect data from [`getrusage`](http://man7.org/linux/man-pages/man2/getrusage.2.html) and that the data is (supposed to be) process bound.

This would be a strong indicator that at least some of the extra CPU processing time is spent within iodine.

There's also the possibility that this issue affects nginx too. It would be nice to see CPU usage for both processes using `top`...?

I guess I'll start building a VM to recreate the issue.

**Comment by Shelvak** [comment]
Thanks for the fast reply.

Rails: 5.2.3 (in Dev & Production env with the same results)
Ruby: 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux] 
Iodine: 0.7.29
Iodine settings (for [1]):
```ruby
  socket_file = '/tmp/server.sock'

  Iodine::DEFAULT_SETTINGS[:port] = 3005 # 0
  # Iodine::DEFAULT_SETTINGS[:address] = socket_file

  Iodine.workers = 3
  Iodine.threads = 5
```
Now that you mention it, I tested with different workers/threads:
1W/1T: `0.000391   0.000074   0.000465 (  2.001261)`
3W/1T: `0.000281   0.000096   0.000377 (  2.002225)`
1W/2T: `1.179701   0.816484   1.996185 (  2.000095)` << problem

So it seems to be the threads... but it only happened with nginx, if I hit the server port it works "fast".

For [2] I'm not stressing the server, I'm trying with just 1 request that in the action only has:
```ruby
def consumption_stats 
   Benchmark.bm do |bm|
      bm.report(:sleep) { sleep 2 }
    end

    render json: { hello: 'world' }
  end
```
I'm attaching you a video to see the htop CPU consumption for nginx and rails with nginx and without (directly via port).
[demo iodine.zip](https://github.com/boazsegev/iodine/files/3228032/demo.iodine.zip)

To put you more in context, in our app we have lines like `%x{ifconfig eth0; sleep 2; ifconfig eth0} ` to show the current bandwidth of each provider or interface, so many users can see the same "stats" and the load average is really high in these cases.

Thanks :+1:

**Comment by boazsegev** [comment]
Interesting... I think Nginx manages to trigger a slow client `ready` event, which routs to the `on_data` event. But since this isn't a slow client and the `on_data` loop is still busy preparing the response, the scheduler reschedules the `on_data` event.

I think nginx might have been messing with the default TCP/IP stack, because slow client events should only occur if clients refuse incoming data (i.e., closed for reading) or read small chunks of data at a time. 

Anyway, since there's only one event, it keeps popping in and out of the event-loop's queue, essentially creating a temporary spin-lock. 

I committed what I think might be a fix. It fixes the issue on my machine, but I didn't test it's effects on other features just yet.

You're welcome to test it on your app.

**Comment by Shelvak** [comment]
Amazing, locally the fix works :D  (I ran bundle install against master)

I'll put master in a client server to test and monitor the stability and the CPU.

Thanks again, I'll update this issue with some results in 2 days :+1:

**Comment by boazsegev** [comment]
Cool! Thanks 👍🏻

**Comment by Shelvak** [comment]
Well the fix is stable and working great.
```ruby
output = `ifconfig eth0`
sleep 2
output += `ifconfig eth0`
# Benchmarks:
  0.006217   0.000000   0.017471 (  2.018075)
  0.006210   0.000000   0.016904 (  2.016776)
  0.005210   0.000217   0.014899 (  2.014509)
  0.006014   0.000316   0.016305 (  2.016249)
```

```ruby
output = `ifconfig eth0; sleep 2; ifconfig eth0`
# Benchmarks:
  0.019202   0.000247   0.028207 (  2.011007)
  0.029553   0.000011   0.036095 (  2.013824)
  0.006324   0.000291   0.026902 (  2.013677)
  0.012517   0.000044   0.028198 (  2.014004)
```

So thank you again for the fast response and fix.

Cheers :beers:

**Comment by boazsegev** [comment]
@Shelvak ,

Thank you for keeping me posted 👍🏻🎉

I'll go ahead and release the updated version.

Kindly,
   Bo.
