### ISSUE TITLE
Don't clobber external namespaces

### ISSUE THREAD

**Issue by WA9ACE** [boazsegev/iodine#80]
There may be other parts of the user's application relying on namespaces, that are being replaced by Iodine, causing them to fail or operate in unexpected ways.

Maybe there's another way to tell Rack Iodine is the priority handler, or not assume when `require`ing Iodine that Rack's WEBrick handler should be overwritten.

Section in reference
https://github.com/boazsegev/iodine/blob/master/lib/rack/handler/iodine.rb#L26

**Comment by boazsegev** [comment]
Hi @WA9ACE ,

Thanks for opening this issue. You're right - it's a good point.

I think this code is a remnant of an issue where setting Rack's default handler wouldn't work with `rackup` for some odd reason.

I'm a bit busy with other things, but feel free to submit a PR if you like. No worries if you don't, I'll get to it (it just might take more time).

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Fix released (version 0.7.36)

Thanks again for he PR!
