### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by Roko131** [boazsegev/iodine#84]
Iodine is an evened server, similar in `it's` architecture to nginx and puma.

Should be:

Iodine is an evened server, similar in `its` architecture to nginx and puma

(its instead of it's)

**Comment by texpert** [comment]
Also, `evened` should be fixed to `evented`.

**Comment by Roko131** [comment]
Also:
By default, iodine is pretty `quite`. Some messages are logged to stderr, but not many.

`quite` should be `quiet`

**Comment by boazsegev** [comment]
Thank you @Roko131  and @texpert  for pointing these out. Fixed in commit 469bdd8.
