### ISSUE TITLE
Trailing ? in URL silently fails

### ISSUE THREAD

**Issue by adam12** [boazsegev/iodine#86]
Hi Bo,

Hope all is well.

I tried to debug and submit a patch for this but I'm not 100% sure where it's occurring in the source code.

Using an incredibly simple Rack application (listed below) as an example, requests to `http://localhost:port/?` (with the trailing `?`) will fail silently, returning an empty reply. If the debugging is cranked up with `-V 5` then the error is logged as `DEBUG (http1.c:671): HTTP parser error.`.

I'm not sure if I'm even in the right area, but I dug into the internals and ended up inside the `consume_request_line` function. At a certain point, it consumes the path from the request and I wasn't able to see where it went. The `on_query` call is never reached as it returns on line 186.

https://github.com/boazsegev/iodine/blob/469bdd82b5ef08d70f693f163dc0254dbe852692/ext/iodine/http1_parser.c#L182-L189

Here's the example Rack application:

```ruby
run ->(env) {
  [200, {}, ["Hello World"]]
}
```

Cheers.

Adam

**Comment by boazsegev** [comment]
Hi Adam,

Thank you for opening this issue. 🙏🏻

I can confirm that I can re-create the issue on my machine.

It seems an edge-case issue, never cropped up in any of my use cases - thanks for discovering it 👏🏻👏🏻🙏🏻

I'll mark this as a bug and look for a solution (though I'm not sure an empty query is legal 🤔, I'm certain it should be supported).

I'll keep you posted.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
The issue was with the `seekch` implementation. The `memchr` based implementation would return the wrong value if the character was found on the starting position 😅

I'll wait for the CI and some tests before I release the fix.

**Comment by boazsegev** [comment]
Released version 0.7.37 with the fix. 🎉

Thanks again for opening this issue 👍🏻🙏🏻

**Comment by adam12** [comment]
I was staring at the `seek2ch` implementation in `gdb` but I didn't see the issue.

Thanks for the quick fix! :100: :+1:
