### ISSUE TITLE
Iodine does not read chunked bodies correctly

### ISSUE THREAD

**Issue by ianks** [boazsegev/iodine#87]
### System Information

 - **OS**:             Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
 - **Ruby**:         2.6.3
 - **Version**:     0.7.37
 - **OpenSSL**:  OpenSSL 1.1.1d  10 Sep 2019

### Description

When the data input has a `Transfer-Encoding: chunked`, Iodine reports the body as being empty. 

### Rack App to Reproduce

```ruby
# config.ru
run ->(env) {
  body = env['rack.input'].read
  prog = File.basename($PROGRAM_NAME)

  puts "(#{prog}) Body is: '#{body}'"
  puts "(#{prog}) Body length is: #{body.length}"

  [200, {}, []]
}
```

### Testing code

```ruby
# run.rb

require 'bundler/inline'

def run_test
  pids = []
  pids << Process.spawn("puma -p 2333 --quiet")
  pids << Process.spawn("iodine -p 2334 -w 1", err: File::NULL)

  sleep 3
  printf "\n" * 3
  puts "===================="
  system 'curl -H "Transfer-Encoding: chunked" -d "payload to send" http://localhost:2333'
  puts "===================="
  system 'curl -H "Transfer-Encoding: chunked" -d "payload to send" http://localhost:2334'
  puts "===================="
  printf "\n" * 3

  sleep 3
  pids.each { |pid| Process.kill('TERM', pid) }
end

gemfile do
  source 'https://rubygems.org'
  gem 'puma'
  gem 'iodine'

  puts Iodine::VERSION
  run_test
end
```

### Expected behavior

Other Rack servers, such as Puma, will read the body to a tempfile so they can be read normally.

### Actual behavior

The body is reported as empty.

**Comment by ianks** [comment]
### Update

I noticed when I toggle `ALLOW_UNALIGNED_MEMORY_ACCESS` to `0`, the spec passes.

**Comment by ianks** [comment]
fixed by #88

**Comment by boazsegev** [comment]
Hi @ianks ,

I pushed updates to fix the issue. However, I think the specs still fail because of an error with the specs.

I wanted your opinion about this.

I think the "large body" specifications fail to `write` the body to the pipe, causing the a smaller body to be written (and, consequently, returned).

There was an issue reading Hex values (chunk length data) and the `Content-Length` header wasn't emitted for `chucked` requests (leading to misinformation in the `env` variable). I think both issues are now resolved.

Could you look at the current GitHub version and see if it solves your issue?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
@ianks 

Thank you for your patience and your help with this!

I'm very bad with the `rspec` code... but it seems the issue occurs only within the testing app.

When I try to perform the tests running an external iodine server (running the app manually and directing the tests to the running app), the current code passes all the tests.

Could you have a look to see if the current (GitHub) version fixes the issue (even though it fails the rspecs on my machine)?

Kindly,
   Bo.

**Comment by boazsegev** [comment]
@ianks ,

Thank you for your patience.

The patch would have been ready sooner, only it seems I've been running my tests against version 0.7.33 ... so tests on my local machine kept failing no matter what I did 🙈 two days lost to foolishness 😒

It seems I'm a mess when it comes to `rspec` 😅

Anyway, I just released the patched version. I hope you enjoy it.

Thank you again!
   Bo.

**Comment by ianks** [comment]
Hey @boazsegev, the best way to run the specs is `bundle exec rake` which will compile the C first. I'll add some documentation for this in the readme.
