### ISSUE TITLE
Why is iodine trying to find the compiler instead of using RbConfig::CONFIG["CC"]?

### ISSUE THREAD

**Issue by eregon** [boazsegev/iodine#91]
See https://github.com/boazsegev/iodine/blob/4219633ab4da37f5029146ab07d07c45862af3fd/ext/iodine/extconf.rb#L3-L28

This seems fragile and suboptimal.
Could the logic be simplified to just using the default `RbConfig::CONFIG["CC"]`, which is the compiler which compiled Ruby?

The current code fails on TruffleRuby because of these hardcoded values:
https://github.com/oracle/truffleruby/issues/2010#issuecomment-629510948

**Comment by boazsegev** [comment]
@eregon ,

Thank you for opening this issue! This is a fair point. 👍🏻

The code you referenced is part of a legacy codebase that was testing if the compiler supports atomics and attempts to locate a compiler that supports atomics (back when gcc-4.9 was the norm).

On the next release, it would be better to avoid this part of the code.

I'll work it in. Thanks! 🙏🏻

Kindly,
   Bo.

**Comment by eregon** [comment]
Thanks for the nice reply, looking forward to that :smiley:

**Comment by boazsegev** [comment]
Possibly fixed in the 0.7.39 version (released today).
🎉👍🏻

@eregon , thanks again for opening this issue 🙏🏻👍🏻
