### ISSUE TITLE
Day is wrong in log date

### ISSUE THREAD

**Issue by fgi** [boazsegev/iodine#92]
### System Information

 - **OS**:             FreeBSD 12.1-RELEASE-p3 GENERIC  amd64
 - **Ruby**:         2.7.1p83
 - **Version**:     0.7.38
 - **OpenSSL**:  1.1.1d-freebsd  10 Sep 2019

### Description

The day in log date is one day before.
Today is Sunday May 17th, 2020, it shows Sunday May 16th.

`X.X.X.X - - [Sun, 16 May 2020 13:10:46 GMT] "GET /robots.txt HTTP/1.1" 200 27b 0ms`

**Comment by boazsegev** [comment]
I confirm this actually occurs.

I'm finishing up a few updates and I'll publish a fix in the coming week or two.

Kindly,
  Bo.

P.S.

A temporary workaround might be to use a middleware for logging requests (like Rails often does). It would be slower and it will consume more memory, but it should work.

**Comment by boazsegev** [comment]
Possibly fixed in the 0.7.39 version (released today) 🎉👍🏻

@fgi , thank you for opening this issue 🙏🏻👍🏻👏🏻

**Comment by fgi** [comment]
@boazsegev That was quick. Thank you!
