### ISSUE TITLE
Unprotected Exception - SystemExit (with rails server)

### ISSUE THREAD

**Issue by Shelvak** [boazsegev/iodine#98]
### System Information

 - **OS**:             Archlinux
 - **Ruby**:         2.7.1 & 2.6.4
 - **Version**:     0.7.41
 - **OpenSSL**:  OpenSSL 1.1.1g  21 Apr 2020

### Description
Hey Bo, sorry to bother  you.

I started using Iodine in a new project, and I'm getting this kind of exception with `Ctrol-c` on server. That always happened to me but I thought that it was because of some gem in the other project.

The "problem"
- Running `rails server`
- Hit `Ctrol-C` shows an exception:
```
=> Booting Rack
=> Rails 6.0.3.2 application starting in development http://0.0.0.0:3000
=> Run `rails server --help` for more startup options
INFO: Listening on port 3000
INFO: Starting up Iodine:
 * Iodine 0.7.41
 * Ruby 2.7.1
 * facil.io 0.7.4 (epoll)
 * 1 Workers X 10 Threads per worker.
 * Maximum 131056 open files / sockets per worker.
 * Master (root) process: 784361.

INFO: Server is running 1 worker X 10 threads with facil.io 0.7.4 (epoll)
* Linked to OpenSSL 1.1.1g  21 Apr 2020
* Detected capacity: 131056 open file limit
* Root pid: 784361
* Press ^C to stop

^CERROR: Iodine caught an unprotected exception - SystemExit: exit
/home/rotsen/.gem/ruby/2.7.1/gems/rack-2.2.3/lib/rack/server.rb:323:in `exit'
/home/rotsen/.gem/ruby/2.7.1/gems/rack-2.2.3/lib/rack/server.rb:323:in `block in start'
/home/rotsen/.gem/ruby/2.7.1/gems/iodine-0.7.41/lib/rack/handler/iodine.rb:13:in `join'
/home/rotsen/.gem/ruby/2.7.1/gems/iodine-0.7.41/lib/rack/handler/iodine.rb:13:in `start'
/home/rotsen/.gem/ruby/2.7.1/gems/iodine-0.7.41/lib/rack/handler/iodine.rb:13:in `run'
/home/rotsen/.gem/ruby/2.7.1/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:39:in `start'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:147:in `block in perform'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:138:in `tap'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:138:in `perform'
/home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/command/base.rb:69:in `perform'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/command.rb:46:in `invoke'
/home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
        from bin/rails:4:in `<main>'
        from bin/rails:4:in `require'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/command.rb:46:in `invoke'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/command/base.rb:69:in `perform'
        from /home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/rotsen/.gem/ruby/2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:138:in `perform'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:138:in `tap'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        from /home/rotsen/.gem/ruby/2.7.1/bundler/gems/rails-2d6a726dcb33/railties/lib/rails/commands/server/server_command.rb:39:in `start'
        from /home/rotsen/.gem/ruby/2.7.1/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
        from /home/rotsen/.gem/ruby/2.7.1/gems/iodine-0.7.41/lib/rack/handler/iodine.rb:13:in `run'
        from /home/rotsen/.gem/ruby/2.7.1/gems/iodine-0.7.41/lib/rack/handler/iodine.rb:13:in `start'
ERROR:

INFO: (784361) detected exit signal.
INFO:    ---  Shutdown Complete  ---

Exiting
```

The "weird" thing is that if I run `bundle exec iodine` the exception didn't appear:
```
INFO: Listening on port 3000
INFO: Starting up Iodine:
 * Iodine 0.7.41
 * Ruby 2.7.1
 * facil.io 0.7.4 (epoll)
 * 1 Workers X 10 Threads per worker.
 * Maximum 131056 open files / sockets per worker.
 * Master (root) process: 784295.

INFO: Server is running 1 worker X 10 threads with facil.io 0.7.4 (epoll)
* Linked to OpenSSL 1.1.1g  21 Apr 2020
* Detected capacity: 131056 open file limit
* Root pid: 784295
* Press ^C to stop


^CINFO: (784295) detected exit signal.
INFO:    ---  Shutdown Complete  ---
```

After a few hours of using the server, I have to keep `Ctrol-c` because in other case the server never exit :man_shrugging:   (attached file)
[iodine-errors.txt](https://github.com/boazsegev/iodine/files/5011459/iodine-errors.txt)

If you need me to test something let me know.

Thanks in advance.
Néstor

### Expected behavior

One `Ctrol-C` finish the server without exceptions

**Comment by boazsegev** [comment]
His @Shelvak ,

Thank you for opening this issue and your question.

However, this isn't an iodine issue, rather it's a feature that exposes an issue with Rack.

Iodine doesn't replace your [calls to `trap`(s)](https://ruby-doc.org/core-2.7.1/Kernel.html#method-i-trap), instead, it installs its own signal handler [in addition to the old one](https://github.com/boazsegev/iodine/blob/5fa13bac8d4f575e9c58a7aafd444a1b6580b469/ext/iodine/fio.c#L1385-L1414).

[Rack, on the other hand, calls `trap` to catch `SIGINT`](https://github.com/rack/rack/blob/649c72bab9e7b50d657b5b432d0c205c95c2be07/lib/rack/server.rb#L319-L325) just in case a server doesn't handle the signal. Perhaps Rack assumes that a server will ignore [`trap`s return value](https://ruby-doc.org/core-2.7.1/Kernel.html#method-i-trap) and override this handler instead of chaining handlers.

Either way, this feature allows you to [handle Ctrl+C in tests and other environments](https://github.com/boazsegev/iodine/issues/59)... though I would recommend using [`Iodine::on_state(: start_shutdown)` or `Iodine::on_state(: on_finish)`](https://www.rubydoc.info/github/boazsegev/iodine/master/Iodine#on_state-class_method) instead.

As a workaround, use `bundle exec iodine` instead. This will also allow for better handling of CLI options (see `iodine -h`).

Kindly,
   Bo.

**Comment by Shelvak** [comment]
Bo, thanks for the reply. Checking the rack code (you pointed), we only need the shutdown method, so I monkeypatched the gem and add:
```ruby
module Iodine
  module Rack
    def self.shutdown
      Iodine.stop
    end
end
```

And that worked as expected  =) So could you put that lines in the rack/iodine.rb file? I can make you a pull-request if you want just with that. If you don't want to dirty the code I can keep the monkeypatch it's not a big deal.

Thanks for the amazing work with the gem.
Cheers.
Néstor

**Comment by boazsegev** [comment]
Thanks!

Somehow I didn't notice that Rack allows servers to avoid this issue.

🎉👏🏻👏🏻🙏🏻👍🏻

**Comment by Shelvak** [comment]
Haha, no problem. Thanks to you :clap:
